Repository Idoo0/neurokit, pull requests merged in 2025-09, with the labels that each got.

#3 feat:onboarding-screen
  assets/images/logo.png
  lib/routes/app_routes.dart
  lib/routes/routes_name.dart
  lib/view/onboarding.dart
  pubspec.yaml
Labels: enhancement

#4 Gal/feat/add onboarding screen
  lib/routes/app_routes.dart
  lib/routes/routes_name.dart
  lib/view/dream_page.dart
  lib/view/introduction_page.dart
  lib/view/onboarding.dart
Labels: enhancement

#6 feat: homepage, Navbar (oveflow)
  assets/icons/badges.svg
  assets/icons/home.svg
  assets/icons/stats.svg
  assets/images/badges.png
  assets/images/home.png
  assets/images/star-sleep.png
  assets/images/stats.png
  lib/components/app_icon.dart
  lib/components/bottom_navbar.dart
  lib/components/mode_picker_sheet.dart
  lib/routes/app_routes.dart
  lib/view/homepage.dart
  pubspec.yaml
Labels: documentation, enhancement

#7 fix button navigation after onboarding to homepage
  lib/view/onboarding_flow.dart
Labels: enhancement

#15 feat: add local storage for warmup results and study session duration
  lib/main.dart
  lib/routes/app_routes.dart
  lib/services/local_storage_service.dart
  lib/view/homepage.dart
  lib/view/study_session_page.dart
  lib/view/study_session_result_page.dart
  lib/view/warmup_page.dart
Labels: enhancement

#16 fix: move fallback to motivation_page
  lib/routes/app_routes.dart
  lib/view/motivation_page.dart
Labels: bug

#26 fix: improve user experience by loading and displaying first name
  lib/view/homepage.dart
Labels: enhancement

#31 Feat/triadi/integration to esp32
  android/app/src/main/AndroidManifest.xml
  lib/controllers/bluetooth_controller.dart
  lib/controllers/session_controller.dart
  lib/main.dart
  lib/models/mode.dart
  lib/models/session_state.dart
  lib/services/ble_service.dart
  lib/services/bt_classic_service.dart
  lib/utils/constants.dart
  lib/view/homepage.dart
  lib/view/study_session_page.dart
  lib/view/study_session_result_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement
